# Generated by Django 5.1.7 on 2025-03-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(default='ETH', max_length=3)),
                ('public_key', models.CharField(max_length=255, unique=True)),
                ('private_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
